require 'open-uri'

Booking.destroy_all
TeachingLanguageSession.destroy_all
DataTeacher.destroy_all
User.destroy_all


# Crear teachers -----------------------------------------------------------------------------------------------------------------------------------------------------
puts "Creando usuarios profesores"

teachers_data = [
  { email: "user1@gmail.com", first_name: "Juan", last_name: "Gómez", country: "España", city: "Madrid", native_language: "español", date_of_birth: "1990-01-15".to_date, about_me: "¡Hola! Soy Juan, un amante de la cultura española. Me encanta la música flamenca y disfruto explorando los rincones históricos de Madrid.", other_languages: "inglés", learning_languages: "francés", teaching_languages: "español", teacher_description: "Profesor de español con experiencia, enfocado en mejorar tu fluidez y comprensión. ¡Vamos a aprender juntos!" , price: 10, file_teacher: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D" },
  { email: "user2@gmail.com", first_name: "María", last_name: "López", country: "México", city: "Ciudad de México", native_language: "español", date_of_birth: "1988-07-22".to_date, about_me: "Saludos, soy María. Enamorada de la riqueza cultural de México, me encanta bailar y experimentar con la deliciosa comida mexicana.", other_languages: "inglés", learning_languages: "francés", teaching_languages: "español", teacher_description: "Profesora de español apasionada por la enseñanza. Descubre la belleza del idioma y sumérgete en la cultura latinoamericana.", price: 12, file_teacher: URI.open("https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=1286&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D")  },
  { email: "user3@gmail.com", first_name: "Carlos", last_name: "Fernández", country: "Argentina", city: "Buenos Aires", native_language: "español", date_of_birth: "1995-03-10".to_date, about_me: "¡Hola! Soy Carlos, un apasionado del tango argentino y un ávido lector de la literatura de Buenos Aires.", other_languages: "inglés", learning_languages: "inglés", teaching_languages: "español", teacher_description: "Maestro de español con enfoque en la cultura argentina. Aprende a hablar español con autenticidad y pasión.", price: 8, file_teacher: URI.open("https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDN8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D")  },
  { email: "user4@gmail.com", first_name: "Ana", last_name: "Martínez", country: "Colombia", city: "Bogotá", native_language: "español", date_of_birth: "1987-12-05".to_date, about_me: "Hola, soy Ana. Me considero una aventurera culinaria y siempre estoy en busca del mejor café colombiano.", other_languages: "inglés", learning_languages: "inglés", teaching_languages: "español", teacher_description: "Profesora de español con amor por la cultura colombiana. ¡Vamos a explorar juntos la riqueza de este hermoso idioma!", price: 25, file_teacher: URI.open("https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDZ8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D") },

  { email: "user5@gmail.com", first_name: "Pedro", last_name: "Rodríguez", country: "Canadá", city: "Ottawa", native_language: "francés", date_of_birth: "1992-09-30".to_date, about_me: "¡Saludos! Soy Pedro, un entusiasta de la historia inca y amante de la naturaleza peruana.", other_languages: "inglés", learning_languages: "español", teaching_languages: "francés", teacher_description: "Maestro de francés con enfoque en la cultura franca. Descubre la belleza de este idioma mientras exploramos la historia canadiense.", price: 14, file_teacher: "https://images.unsplash.com/photo-1521119989659-a83eee488004?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTB8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D" },
  { email: "user6@gmail.com", first_name: "Laura", last_name: "González", country: "Francia", city: "París", native_language: "francés", date_of_birth: "1998-04-18".to_date, about_me: "Hola, soy Laura. Admiro la diversidad cultural de Venezuela y trabajo como activista por los derechos humanos.", other_languages: "inglés", learning_languages: "español", teaching_languages: "francés", teacher_description: "Profesora de francés comprometida con la justicia social. ¡Descubre la lengua mientras exploramos la cultura francesa!", price: 17, file_teacher: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTh8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D" },
  { email: "user7@gmail.com", first_name: "Diego", last_name: "Díaz", country: "Canadá", city: "Ottawa", native_language: "francés", date_of_birth: "1985-11-12".to_date, about_me: "¡Hola a todos! Soy Diego, un aficionado al vino chileno y un amante de la majestuosa cordillera de los Andes.", other_languages: "inglés", learning_languages: "alemán", teaching_languages: "francés", teacher_description: "Maestro de francés y amante del vino. Descubre la riqueza del idioma mientras exploramos la belleza de canada.", price: 25, file_teacher: "https://images.unsplash.com/photo-1615813967515-e1838c1c5116?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTl8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D" },
  { email: "user8@gmail.com", first_name: "Isabel", last_name: "Hernández", country: "Francia", city: "París", native_language: "francés", date_of_birth: "1993-06-25".to_date, about_me: "Saludos, soy Isabel. Defiendo la biodiversidad ecuatoriana y disfruto explorando la belleza natural a través del ecoturismo.", other_languages: "inglés", learning_languages: "alemán", teaching_languages: "francés", teacher_description: "Profesora de francés y amante de la naturaleza. ¡Aprende el idioma mientras exploramos la diversidad de francia!", price: 25, file_teacher: "https://images.unsplash.com/photo-1589571894960-20bbe2828d0a?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjB8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D" },

  { email: "user9@gmail.com", first_name: "Luis", last_name: "Suárez", country: "Australia", city: "Canberra", native_language: "inglés", date_of_birth: "1989-08-07".to_date, about_me: "¡Hola a todos! Soy Luis, un apasionado de la arqueología maya y me encanta sumergirme en la música tradicional.", other_languages: "español", learning_languages: "alemán", teaching_languages: "inglés", teacher_description: "Maestro de inglés con amor por la arqueología. ¡Descubre la riqueza de la cultura maya mientras aprendemos el idioma!", price: 12, file_teacher: "https://images.unsplash.com/photo-1488161628813-04466f872be2?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NzR8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D" },
  { email: "user10@gmail.com", first_name: "Elena", last_name: "Pérez", country: "Australia", city: "Canberra", native_language: "inglés", date_of_birth: "1996-02-14".to_date, about_me: "Hola, soy Elena. Amo la danza salsa y siempre estoy orgullosa de compartir la rica cultura.", other_languages: "español", learning_languages: "español", teaching_languages: "inglés", teacher_description: "Profesora de inglés y bailarina de salsa. ¡Aprende el idioma mientras disfrutamos de la música y el baile australiano!", price: 13, file_teacher: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODB8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D" },
  { email: "user11@gmail.com", first_name: "Federico", last_name: "Alvarez", country: "Estados Unidos", city: "Washington, D.C.", native_language: "inglés", date_of_birth: "1986-10-03".to_date, about_me: "Greetings! I'm Federico, passionate about international politics and urban photography. Excited to explore the diverse culture of Washington, D.C.", other_languages: "alemán", learning_languages: "español", teaching_languages: "inglés", teacher_description: "Experienced English teacher with a focus on practical communication skills. Let's improve your English together!", price: 18, file_teacher: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nzl8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D" },
  { email: "user12@gmail.com", first_name: "Camila", last_name: "Flores", country: "Reino Unido", city: "Londres", native_language: "inglés", date_of_birth: "1991-04-28".to_date, about_me: "Hello, I'm Camila. A Shakespeare enthusiast and an explorer of the charming British pubs. Join me for a cultural journey in London!", other_languages: "alemán", learning_languages: "español", teaching_languages: "inglés", teacher_description: "Native English speaker with a passion for literature. Let's enhance your English skills through engaging conversations and storytelling.", price: 7, file_teacher: "https://images.unsplash.com/photo-1542596768-5d1d21f1cf98?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODh8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D" },

  { email: "user13@gmail.com", first_name: "Roberto", last_name: "Santos", country: "Alemania", city: "Berlín", native_language: "alemán", date_of_birth: "1994-11-08".to_date, about_me: "Hey there! I'm Roberto, an avid fan of winter sports and a nature lover. Let's explore the breathtaking Canadian landscapes together.", other_languages: "inglés", learning_languages: "español", teaching_languages: "alemán", teacher_description: "Outdoor enthusiast and English teacher. Improve your language skills while enjoying the beauty of Canada's nature.", price: 9, file_teacher: "https://images.unsplash.com/photo-1492288991661-058aa541ff43?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTV8fHBlcnNvbmF8ZW58MHx8MHx8fDA%3D" },
  { email: "user14@gmail.com", first_name: "Claudia", last_name: "Moreno", country: "Alemania", city: "Berlín", native_language: "alemán", date_of_birth: "1984-06-19".to_date, about_me: "G'day! I'm Claudia, an explorer of Australian wildlife and a passionate surfer. Join me for an adventure Down Under!", other_languages: "inglés", learning_languages: "español", teaching_languages: "alemán", teacher_description: "Australian English teacher with a love for nature. Let's improve your language skills while discovering the beauty of Australia.", price: 11, file_teacher: "https://images.unsplash.com/photo-1618835962148-cf177563c6c0?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTAyfHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "user15@gmail.com", first_name: "Javier", last_name: "Jiménez", country: "Alemania", city: "Berlíni", native_language: "alemán", date_of_birth: "1983-01-12".to_date, about_me: "Hello, I'm Javier. Passionate about the diverse culture of India and an avid collector of stories. Let's discover the wonders of New Delhi together!", other_languages: "inglés", learning_languages: "español", teaching_languages: "alemán", teacher_description: "English teacher with a fascination for Indian culture. Let's enhance your language skills while exploring the beauty of New Delhi.", price: 8, file_teacher: "https://images.unsplash.com/photo-1549068106-b024baf5062d?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTExfHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "user16@gmail.com", first_name: "Patricia", last_name: "Castro", country: "Alemania", city: "Berlín", native_language: "alemán", date_of_birth: "1997-07-01".to_date, about_me: "Mis clases van más allá de la gramática y el vocabulario; te sumergirás en la cultura alemana a través de literatura.", other_languages: "inglés", learning_languages: "español", teaching_languages: "alemán", teacher_description: "Professeur de français passionné par la culture parisienne. Améliorons ensemble vos compétences linguistiques!", price: 10, file_teacher: "https://images.unsplash.com/photo-1597586124394-fbd6ef244026?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTI0fHxwZXJzb25hfGVufDB8fDB8fHww" },
  
  { email: "user17@gmail.com", first_name: "Martín", last_name: "Leroy", country: "Bélgica", city: "Bruselas", native_language: "francés", date_of_birth: "1992-03-19".to_date, about_me: "Salut! Je suis Martín, passionné par la bande dessinée belge et amateur de chocolat. Rejoignez-moi pour une exploration culturelle à Bruxelles!", other_languages: "inglés", learning_languages: "español", teaching_languages: "francés", teacher_description: "Professeur de français et espagnol. Plongeons dans la richesse de la bande dessinée belge et de la culture espagnole ensemble!", price: 13, file_teacher: "https://images.unsplash.com/photo-1563584316028-2b70b3a3a8bf?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTM0fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "user18@gmail.com", first_name: "Sophie", last_name: "Müller", country: "Alemania", city: "Berlín", native_language: "alemán", date_of_birth: "1989-08-14".to_date, about_me: "Hallo, ich bin Sophie. Ich liebe die deutsche Geschichte und erkunde gerne die künstlerische Szene in Berlin. Begleite mich auf eine kulturelle Reise!", other_languages: "inglés", learning_languages: "español",  teaching_languages: "francés", teacher_description: "Aprender español para sumergirme en la cultura y la historia de España.", price: 11, file_teacher: "https://images.unsplash.com/photo-1589696485114-9e2f81d83484?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTM2fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "user19@gmail.com", first_name: "Giorgio", last_name: "Ricci", country: "Italia", city: "Roma", native_language: "italiano", date_of_birth: "1993-12-08".to_date, about_me: "Ciao, sono Giorgio. Appassionato di arte e storia italiana, esploro le strade di Roma in cerca di nuove scoperte. Unisciti a me in questo viaggio culturale!", other_languages: "inglés", learning_languages: "español",  teaching_languages: "francés", teacher_description: "Desarrollar habilidades en francés para explorar la rica literatura y la escena artística de Francia.", price: 7, file_teacher: "https://images.unsplash.com/photo-1542838686-37da4a9fd1b3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTY3fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "user20@gmail.com", first_name: "Mia", last_name: "Andersen", country: "Dinamarca", city: "Copenhague", native_language: "danés", date_of_birth: "1996-06-25".to_date, about_me: "Hej, jeg er Mia. Jeg elsker den danske hygge og udforsker gerne de historiske steder i København. Kom med på en kulturel rejse!", other_languages: "inglés", learning_languages: "español",  teaching_languages: "francés", teacher_description: "Mejorar mi sueco para conectarme con la cultura y la historia de Suecia.", price: 9, file_teacher: "https://images.unsplash.com/photo-1548142542-c53707f8b05b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTcxfHxwZXJzb25hfGVufDB8fDB8fHww" },
]

teachers_data.each do |teacher_info|
  user_teacher = User.create!(
    email: teacher_info[:email],
    role: 1,
    password: "123456",
    first_name: teacher_info[:first_name],
    last_name: teacher_info[:last_name],
    country: teacher_info[:country],
    city: teacher_info[:city],
    date_of_birth: teacher_info[:date_of_birth],
    about_me: teacher_info[:about_me],
    native_language: teacher_info[:native_language],
    other_languages: teacher_info[:other_languages],
    learning_languages: teacher_info[:learning_languages],
    objectives: "poliglota"
  )

  file_teacher = URI.open(teacher_info[:file_teacher])
  user_teacher.photo.attach(io: file_teacher, filename: "#{teacher_info[:first_name].downcase}_image.png", content_type: "image/png")
  user_teacher.save!


  teacher_data = DataTeacher.create!(
    teaching_languages: teacher_info[:teaching_languages],
    teacher_description: teacher_info[:teacher_description],
    usd_per_hour: teacher_info[:price],
    user: user_teacher
  )

  puts "creando  TeachingLanguageSession"
  TeachingLanguageSession.create!(language: teacher_info[:teaching_languages], user: user_teacher)
end



# Crear students -----------------------------------------------------------------------------------------------------------------------------------------------------
puts "Creando usuarios estudiantes"

students_data = [
  { email: "student1@gmail.com", first_name: "Lucho", last_name: "Gómez", country: "España", city: "Madrid", native_language: "español", date_of_birth: "1990-01-15".to_date, about_me: "¡Hola! Soy Juan, un amante de la cultura española. Me encanta la música flamenca y disfruto explorando los rincones históricos de Madrid.", other_languages: "inglés", learning_languages: "francés", file_teacher: "https://images.unsplash.com/photo-1563240619-44ec0047592c?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTgyfHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student2@gmail.com", first_name: "Maríana", last_name: "López", country: "México", city: "Ciudad de México", native_language: "español", date_of_birth: "1988-07-22".to_date, about_me: "Saludos, soy María. Enamorada de la riqueza cultural de México, me encanta bailar y experimentar con la deliciosa comida mexicana.", other_languages: "inglés", learning_languages: "francés", file_teacher: "https://images.unsplash.com/photo-1601412436009-d964bd02edbc?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTg0fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student3@gmail.com", first_name: "Carloto", last_name: "Fernánd", country: "Argentina", city: "Buenos Aires", native_language: "español", date_of_birth: "1995-03-10".to_date, about_me: "¡Hola! Soy Carlos, un apasionado del tango argentino y un ávido lector de la literatura de Buenos Aires.", other_languages: "inglés", learning_languages: "inglés", file_teacher: "https://images.unsplash.com/photo-1502791451862-7bd8c1df43a7?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTk2fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student4@gmail.com", first_name: "Anam", last_name: "Martínez", country: "Colombia", city: "Bogotá", native_language: "español", date_of_birth: "1987-12-05".to_date, about_me: "Hola, soy Ana. Me considero una aventurera culinaria y siempre estoy en busca del mejor café colombiano.", other_languages: "inglés", learning_languages: "inglés", file_teacher: "https://images.unsplash.com/photo-1612469294274-b1baaf5125ca?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTkyfHxwZXJzb25hfGVufDB8fDB8fHww" },

  { email: "student5@gmail.com", first_name: "Pedrito", last_name: "Rodríguez", country: "Canadá", city: "Ottawa", native_language: "francés", date_of_birth: "1992-09-30".to_date, about_me: "¡Saludos! Soy Pedro, un entusiasta de la historia inca y amante de la naturaleza peruana.", other_languages: "inglés", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1537511446984-935f663eb1f4?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjA0fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student6@gmail.com", first_name: "Lauri", last_name: "González", country: "Francia", city: "París", native_language: "francés", date_of_birth: "1998-04-18".to_date, about_me: "Hola, soy Laura. Admiro la diversidad cultural de Venezuela y trabajo como activista por los derechos humanos.", other_languages: "inglés", learning_languages: "español", file_teacher: "https://plus.unsplash.com/premium_photo-1689551670902-19b441a6afde?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjAxfHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student7@gmail.com", first_name: "Diego", last_name: "Díaz", country: "Canadá", city: "Ottawa", native_language: "francés", date_of_birth: "1985-11-12".to_date, about_me: "¡Hola a todos! Soy Diego, un aficionado al vino chileno y un amante de la majestuosa cordillera de los Andes.", other_languages: "inglés", learning_languages: "alemán", file_teacher: "https://plus.unsplash.com/premium_photo-1689977968861-9c91dbb16049?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjA1fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "studentr8@gmail.com", first_name: "Isabela", last_name: "Hernández", country: "Francia", city: "París", native_language: "francés", date_of_birth: "1993-06-25".to_date, about_me: "Saludos, soy Isabel. Defiendo la biodiversidad ecuatoriana y disfruto explorando la belleza natural a través del ecoturismo.", other_languages: "inglés", learning_languages: "alemán", file_teacher: "https://images.unsplash.com/photo-1613566028327-4a32e02f6ab1?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjA4fHxwZXJzb25hfGVufDB8fDB8fHww" },

  { email: "student9@gmail.com", first_name: "Lui", last_name: "Suárez", country: "Australia", city: "Canberra", native_language: "inglés", date_of_birth: "1989-08-07".to_date, about_me: "¡Hola a todos! Soy Luis, un apasionado de la arqueología maya y me encanta sumergirme en la música tradicional.", other_languages: "español", learning_languages: "alemán", file_teacher: "https://images.unsplash.com/photo-1548544149-4835e62ee5b3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjIyfHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student10@gmail.com", first_name: "Elena", last_name: "Pérez", country: "Australia", city: "Canberra", native_language: "inglés", date_of_birth: "1996-02-14".to_date, about_me: "Hola, soy Elena. Amo la danza salsa y siempre estoy orgullosa de compartir la rica cultura.", other_languages: "español", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjExfHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student11@gmail.com", first_name: "Federino", last_name: "Alvarez", country: "Estados Unidos", city: "Washington, D.C.", native_language: "inglés", date_of_birth: "1986-10-03".to_date, about_me: "Greetings! I'm Federico, passionate about international politics and urban photography. Excited to explore the diverse culture of Washington, D.C.", other_languages: "alemán", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1546820389-44d77e1f3b31?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjMwfHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student12@gmail.com", first_name: "Cami", last_name: "Flores", country: "Reino Unido", city: "Londres", native_language: "inglés", date_of_birth: "1991-04-28".to_date, about_me: "Hello, I'm Camila. A Shakespeare enthusiast and an explorer of the charming British pubs. Join me for a cultural journey in London!", other_languages: "alemán", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1596815064285-45ed8a9c0463?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjMxfHxwZXJzb25hfGVufDB8fDB8fHww" },

  { email: "student13@gmail.com", first_name: "Robert", last_name: "Santos", country: "Alemania", city: "Berlín", native_language: "alemán", date_of_birth: "1994-11-08".to_date, about_me: "Hey there! I'm Roberto, an avid fan of winter sports and a nature lover. Let's explore the breathtaking Canadian landscapes together.", other_languages: "inglés", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1614008516609-542a07c7b701?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjM0fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student14@gmail.com", first_name: "Claudia", last_name: "Moreno", country: "Alemania", city: "Berlín", native_language: "alemán", date_of_birth: "1984-06-19".to_date, about_me: "G'day! I'm Claudia, an explorer of Australian wildlife and a passionate surfer. Join me for an adventure Down Under!", other_languages: "inglés", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjM5fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student15@gmail.com", first_name: "Javi", last_name: "Jiménez", country: "Alemania", city: "Berlíni", native_language: "alemán", date_of_birth: "1983-01-12".to_date, about_me: "Hello, I'm Javier. Passionate about the diverse culture of India and an avid collector of stories. Let's discover the wonders of New Delhi together!", other_languages: "inglés", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1564974288343-7cce73c4b71a?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjQyfHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student16@gmail.com", first_name: "Patric", last_name: "Castro", country: "Alemania", city: "Berlín", native_language: "alemán", date_of_birth: "1997-07-01".to_date, about_me: "Mis clases van más allá de la gramática y el vocabulario; te sumergirás en la cultura alemana a través de literatura.", other_languages: "inglés", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1512310604669-443f26c35f52?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjQwfHxwZXJzb25hfGVufDB8fDB8fHww" },
  
  { email: "student17@gmail.com", first_name: "Martí", last_name: "Leroy", country: "Bélgica", city: "Bruselas", native_language: "francés", date_of_birth: "1992-03-19".to_date, about_me: "Salut! Je suis Martín, passionné par la bande dessinée belge et amateur de chocolat. Rejoignez-moi pour une exploration culturelle à Bruxelles!", other_languages: "inglés", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjQzfHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student18@gmail.com", first_name: "Sophia", last_name: "Müller", country: "Alemania", city: "Berlín", native_language: "alemán", date_of_birth: "1989-08-14".to_date, about_me: "Hallo, ich bin Sophie. Ich liebe die deutsche Geschichte und erkunde gerne die künstlerische Szene in Berlin. Begleite mich auf eine kulturelle Reise!", other_languages: "inglés", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1526413232644-8a40f03cc03b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjQ2fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student19@gmail.com", first_name: "Giorgio", last_name: "Ricci", country: "Italia", city: "Roma", native_language: "italiano", date_of_birth: "1993-12-08".to_date, about_me: "Ciao, sono Giorgio. Appassionato di arte e storia italiana, esploro le strade di Roma in cerca di nuove scoperte. Unisciti a me in questo viaggio culturale!", other_languages: "inglés", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1548280684-8c051518e195?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjQ3fHxwZXJzb25hfGVufDB8fDB8fHww" },
  { email: "student20@gmail.com", first_name: "Mirian", last_name: "Andersen", country: "Dinamarca", city: "Copenhague", native_language: "danés", date_of_birth: "1996-06-25".to_date, about_me: "Hej, jeg er Mia. Jeg elsker den danske hygge og udforsker gerne de historiske steder i København. Kom med på en kulturel rejse!", other_languages: "inglés", learning_languages: "español", file_teacher: "https://images.unsplash.com/photo-1601412436405-1f0c6b50921f?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjU1fHxwZXJzb25hfGVufDB8fDB8fHww" },
]

students_data.each do |student_info|
  user_student = User.create!(
    email: student_info[:email],
    role: 0,
    password: "123456",
    first_name: student_info[:first_name],
    last_name: student_info[:last_name],
    country: student_info[:country],
    city: student_info[:city],
    date_of_birth: student_info[:date_of_birth],
    about_me: student_info[:about_me],
    native_language: student_info[:native_language],
    other_languages: student_info[:other_languages],
    learning_languages: student_info[:learning_languages],
    objectives: "poliglota"
  )

  file_student = URI.open(student_info[:file_teacher])
  user_student.photo.attach(io: file_student, filename: "#{student_info[:first_name].downcase}_image.png", content_type: "image/png")
  user_student.save!

  puts "creando bookings"

  teaching_language_sessions = user_student.teaching_language_sessions

  teaching_language_sessions.each do |teaching_language_session|
    Booking.create!(
      user: user_student,
      teaching_language_session: teaching_language_session,
      date: "2023-12-17".to_date, 
      time_in: "19:00:00 -0300".to_time  
    )
  end
end

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  # # Adjuntar la bandera al usuario
  # country_flag_url = country_flag_icon_url(user_student.country_code.downcase) rescue nil
  # user_student.update(country_flag_url: country_flag_url) if country_flag_url

